### ISSUE TITLE
After a while `launchMainActivity` starts failed 

### ISSUE THREAD

**Issue by cnyunguo** [jiusanzhou/flutter_floatwing#10]
长时间（10分钟）运行之后，launchMainActivity会无法唤起。

**Comment by jiusanzhou** [comment]
Please have a try for version `v0.2.1`.

**Comment by jiusanzhou** [comment]
@cnyunguo  Please feedback if the `v0.2.1` version works well.

**Comment by cnyunguo** [comment]
[https://c.c-cee.com/WeChat_20220826194129.mp4](https://c.c-cee.com/WeChat_20220826194129.mp4)
拖拽悬浮窗后，再点击悬浮窗之后无法触发tap事件，这是我录屏演示的视频。
下面是日志：

[https://c.c-cee.com/run.log](https://c.c-cee.com/run.log)

**Comment by cnyunguo** [comment]
已解决
