### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by VolodymyrMaiakov** [jiusanzhou/flutter_floatwing#2]
flutter_floatwing-main\android\src\main\kotlin\im\zoe\labs\flutter_floatwing\FloatwingService.kt: (128, 32): Type mismatch: inferred type is Map<*, *>? but Map<*, *> was expected

**Comment by jiusanzhou** [comment]
Hi @VolodimirMaiakov, thank you for your attention. This may be a issue with version of Kotlin, I will try to fix it in a few days.

**Comment by jiusanzhou** [comment]
hey @VolodimirMaiakov  can you help me to test it, i can't reproduce this issue.
you can clone this repo `https://github.com/jiusanzhou/flutter_floatwing` and checkout to `hotfix/build-failed` branch,
then build the example.

Thank you so much.

**Comment by VolodymyrMaiakov** [comment]
Example compiled successfully. Thanks.

**Comment by jiusanzhou** [comment]
Okay. I will release a new version. Thank you for your help
